#!/bin/sh

DICT=$1

if [ "x${DICT}" = "x" ]; then
    echo "Need a jargon-formatted text file to write out."
    exit 1
fi

BARENAME=$(basename -s .txt ${DICT})
DBPATH="/var/lib/go-dictd/${BARENAME}.ldb"

echo "Dict file:   '${DICT}'"
echo "Name:        ${BARENAME}"
echo "DBPath:      ${DBPATH}"
echo ""
echo "  (Hit <enter> if this is good)"
echo ""

read fnord

go-dictd-load ${DBPATH} ${DICT}
chown -R dictd:root ${DBPATH}

echo ""
echo "   Add this entry into Databases in /var/lib/go-dictd/config.json"
echo ""

cat <<EOF
   {"Name": "${BARENAME}",
    "Path": "${DBPATH}",
    "Desc": "Describe this Here"},
EOF

echo ""
echo ""
echo ""
